### ISSUE TITLE
Specio::Declare::inline() documentation bug?

### ISSUE THREAD

**Issue by cxw42** [houseabsolute/Specio#13]
I am working on [Class::Tiny::ConstrainedAccessor](https://metacpan.org/pod/Class::Tiny::ConstrainedAccessor), which can (among other things) apply Specio constraints to Class::Tiny classes.  The `inline` parameter to [Specio::Declare::declare()](https://metacpan.org/pod/Specio::Declare#declare(...)) comes with a code example:

>     sub {    
>        my $self = shift;
>        my $var  = shift;
>        return $_[0]->parent->inline_check( $_[1] )
>                . ' and more checking code goes here';
>     }

I am confused by the use of `shift` along with `$_[]`.  Should the declarations be `my ($self, $var) = @_;` instead?  Or is the inline generator receiving four parameters instead of two?  Thanks!

**Edit** An example: the following works:

    use 5.006; use strict; use warnings; use Scalar::Util qw(looks_like_number);
    
    use parent "Specio::Exporter";
    use Specio::Declare;
    use Specio::Library::Builtins;
    
    declare("MediumIntegerInline",
        inline => sub {
            my ($self, $var) = @_;      # <===== Not shifting off $_[0] and $_[1]
            return qq[(
                Scalar::Util::looks_like_number($var) &&
                    ($var >= 10) && ($var < 20)
            )];
        },
    );

    for(qw(MediumIntegerInline)) {
        t($_)->validate_or_die(15);
        t($_)->value_is_valid(0) and die "Unexpected validation success in $_";
    }

**Comment by autarch** [comment]
Yeah, that definitely looks like a bug. It should either use shift or use `@_` in place.
