### ISSUE TITLE
Centos 7.3 / perl 5.16 claims List::Util does not export "all"

### ISSUE THREAD

**Issue by halindrome** [houseabsolute/Specio#5]
Doing an install of various modules, DateTime seems to rely upon this module.  However, this module (in OO.pm) seems to try to bring in List::Util qw(all) and List::Util complains that it does not export "all".

**Comment by halindrome** [comment]
Actually, the problem MAY be that the system version of List::Util is very old on Centos 7.x and it is conflicting with a locally installed version.  Please ignore this while I investigate further.

**Comment by autarch** [comment]
The distro depends on List::Util 1.33, which is when `all` was added, so I think this is a problem with your installation or your toolchain modules or something. I'm inclined to close this issue.

**Comment by halindrome** [comment]
Me too - sorry for the noise.
